function createfigure(xdata1, ydata1, zdata1, XMatrix1, YMatrix1, ZMatrix1, xdata2, xdata3, X1, U1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, XMATRIX1, YMATRIX1, ZMATRIX1, XDATA2, XDATA3, X1, U1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data
%  XDATA2:  surface xdata
%  XDATA3:  surface xdata
%  X1:  quiver3 x
%  U1:  quiver3 u

%  Auto-generated by MATLAB on 01-May-2017 15:33:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
axis off
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,...
    'FaceColor',[0.313725501298904 0.313725501298904 0.313725501298904],...
    'EdgeColor',[0.24705882370472 0.24705882370472 0.24705882370472]);

% Create multiple lines using matrix input to plot3
plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',axes1,'LineStyle','--',...
    'Color',[0 0 0]);

% Create surf
surf(xdata2,ydata1,zdata1,'Parent',axes1,...
    'FaceColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'EdgeColor',[0.313725501298904 0.313725501298904 0.313725501298904]);

% Create surf
surf(xdata3,ydata1,zdata1,'Parent',axes1,...
    'FaceColor',[0.831372559070587 0.815686285495758 0.7843137383461],...
    'EdgeColor',[0.313725501298904 0.313725501298904 0.313725501298904]);

% Create quiver3
quiver3(X1,X1,X1,U1,X1,X1,'MaxHeadSize',2,'LineWidth',2.5,...
    'AutoScaleFactor',0.5);

% Create xlabel
xlabel('x','Visible','off');

% Create zlabel
zlabel('z','Visible','off');

% Create ylabel
ylabel('y','Visible','off');

view(axes1,[39.3 8.4]);
axis(axes1,'ij');
